version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html/hyhaus
permissions:
  - object: /var/www/html
    owner: root
    group: root
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu
